#!/usr/bin/env bash

declare -a TERMCAPS=(
    LESS_TERMCAP_vb
    LESS_TERMCAP_mb
    LESS_TERMCAP_md
    LESS_TERMCAP_me
    LESS_TERMCAP_so
    LESS_TERMCAP_se
    LESS_TERMCAP_us
    LESS_TERMCAP_ue
)
